# Narwall are awsime!
# Version 1.2.1

Server Admins:
    - 580baby
    - Bigthundermtn
    - SGT_Panda_Tech
Welcome Message: '&5Ladies and Gentlemen, Please Welcome '
Welcome Message2: '&5 To the Server!'
Goodbye Message: '&5 Ladies and Gentlemen, I would ask you to say goodbye to '
Goodbye Message2: '&5 but they already left the server!'
health_display: true